CREATE TABLE aluno
(
    codigo INTEGER NOT NULL,
    nome VARCHAR(100) NOT NULL,
    ra VARCHAR(20) NOT NULL,
    PRIMARY KEY (codigo)
)


INSERT INTO aluno VALUES (1, "Ana", 123456);
INSERT INTO aluno VALUES (2, "Joao", 234567);
INSERT INTO aluno VALUES (3, "Pedro", 654321);